name: backend-pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.19.1]
        mongodb-version: ['6.0']

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install dependencies
        run: npm install
        env:
          DB_URI: mongodb://127.0.0.1:27017/astro-db
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build image and push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: ghcr.io
          repository: mhmdksh/Astrolabs-Backend-Nodejs
          add_git_labels: true
          tag_with_ref: true
          tag_with_sha: true

  deploy:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Redeploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.MY_HOST }}
          username: ${{ secrets.MY_USERNAME }}
          key: ${{ secrets.MY_PRIVATE_KEY_ALL }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo su
            cd ~/Astrolabs-Backend-Nodejs
            docker compose down
            git pull
            docker compose up -d --build
            docker image prune -a --force
